name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/user
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: user
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/user/user/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/user

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      # Push to dockerhub
      - name: Push user to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          file: docker/user/Dockerfile-release
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Push user-db to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: false
          dockerfile: docker/user-db/Dockerfile
          path: docker/user-db
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true

